name: Laravel

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, sqlite, bcmath
          ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=1G
          coverage: xdebug
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Create SQLite Database
        run: |
          touch database/database.sqlite
          php artisan migrate --force

      # only run this step if you want to put some data in the database on a deployed instance of app. So, for demoing to a client, this is a good idea, but for a new production intsance, no seed data should be needed. Check the seeders/DatabaseSeeder.php file to see if the seed command is commented out or not.
      # - name: Seed Database
      #   run: php artisan db:seed --force
      # make sure the seed command is not commented out in the seeders/DatabaseSeeder.php file

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Node.js Dependencies
        run: npm install

      - name: Build Assets
        run: npm run build

      - name: Run Tests
        run: php artisan test
