name: Laravel

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  
        extensions: mbstring, pdo, sqlite, bcmath
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=1G
        coverage: xdebug
        tools: composer:v2

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Create SQLite Database
      run: |
        touch database/database.sqlite
        php artisan migrate

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build

    - name: Run Tests
      run: php artisan test
